// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWPFpYA-UkQ7fT1CDorcM3_-ad4TIr9Ic',
    appId: '1:1083297956269:web:ee828f5d3d465352546124',
    messagingSenderId: '1083297956269',
    projectId: 'trip-planner-2775c',
    authDomain: 'trip-planner-2775c.firebaseapp.com',
    storageBucket: 'trip-planner-2775c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnnUEAuNqGeshBdB9xiC1leCZH_cgdc5o',
    appId: '1:1083297956269:android:d3730b51bf88cc89546124',
    messagingSenderId: '1083297956269',
    projectId: 'trip-planner-2775c',
    storageBucket: 'trip-planner-2775c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZzbNCaYWeEXoJCuWdN-2NvrxM4OcPWOw',
    appId: '1:1083297956269:ios:5fcda725e5fed437546124',
    messagingSenderId: '1083297956269',
    projectId: 'trip-planner-2775c',
    storageBucket: 'trip-planner-2775c.firebasestorage.app',
    androidClientId: '1083297956269-bjjmla0cp9tf1m6db7cvnt289cu3tvko.apps.googleusercontent.com',
    iosClientId: '1083297956269-75n9c2u9ckre8uciha8uqase4ii66g84.apps.googleusercontent.com',
    iosBundleId: 'com.example.tripPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZzbNCaYWeEXoJCuWdN-2NvrxM4OcPWOw',
    appId: '1:1083297956269:ios:5fcda725e5fed437546124',
    messagingSenderId: '1083297956269',
    projectId: 'trip-planner-2775c',
    storageBucket: 'trip-planner-2775c.firebasestorage.app',
    androidClientId: '1083297956269-bjjmla0cp9tf1m6db7cvnt289cu3tvko.apps.googleusercontent.com',
    iosClientId: '1083297956269-75n9c2u9ckre8uciha8uqase4ii66g84.apps.googleusercontent.com',
    iosBundleId: 'com.example.tripPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWPFpYA-UkQ7fT1CDorcM3_-ad4TIr9Ic',
    appId: '1:1083297956269:web:074d6aeb71ca5dc6546124',
    messagingSenderId: '1083297956269',
    projectId: 'trip-planner-2775c',
    authDomain: 'trip-planner-2775c.firebaseapp.com',
    storageBucket: 'trip-planner-2775c.firebasestorage.app',
  );
}
